### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jordanbrown** [d-ronnqvist/blogpost-codesample-PullToRefresh#1]
Did you use a tool to make up the paths for each letter? Or did you do it all manually? 

https://github.com/d-ronnqvist/blogpost-codesample-PullToRefresh/blob/master/PullToRefreshAnimation/PullToRefreshAnimation/SampleViewController.m#L310

**Comment by d-ronnqvist** [comment]
It's a little bit of both, some tools that helped me along the way and a good bit of manual work as well.

## Creating the vector path

I started out in an app called Sketch and wrote the text "Loading" in a font called PilGi (that I had on my system but I don't remember how I got it).

![Base text](https://f.cloud.github.com/assets/1228143/2116985/db36706a-90ac-11e3-8ed1-98526fc08b8e.png)

Then, in the same app I manually traced the text in two parts: "Load" and "ing":

![Tracing "Load"](https://f.cloud.github.com/assets/1228143/2117003/3f90b588-90ae-11e3-9d24-bb74597f3a99.png)

![Tracing "ing"](https://f.cloud.github.com/assets/1228143/2117004/45b8d29c-90ae-11e3-91ce-53254d32714f.png)

As you can see I made some deviations from the original font, especially on the _L_, _o_, and _g_.

At this point I had 4 elements in my file: the original text, the path for Load, the path for ing (without the dot), and the dot over the i.

![The different element in my file](https://f.cloud.github.com/assets/1228143/2117008/d2b9d84e-90ae-11e3-9393-6ecdd20c8573.png)

I hid the text and manually adjusted the vector paths until I liked the flow of the text

![The final result in Sketch](https://f.cloud.github.com/assets/1228143/2117009/de52b36a-90ae-11e3-92c3-ffa5f3ce4323.png)

## Converting to CGPath code

I then exported vector paths form above into a SVG and opened it in a simple text editor to copy and paste only the path data without all the other SVG data. This is the part of the file that I was interested in:

![vector data in SVG](https://f.cloud.github.com/assets/1228143/2117044/a8ff75e8-90b0-11e3-8be7-350c256b99de.png)

I pasted it into an app called Patterns which work with regular expressions and used a couple of regular expressions similar to the ones in the image below to convert `Mx,y` into `CGPathMoveToPoint(path, NULL, x, y);` and things like `Lx,y` into `CGPathAddLineToPoint(path, NULL, x, y);` and similar. At each step I took the result and used it as the source for the next replacement:

`M(-?\d+\.\d*),(-?\d+\.\d*)\s`
into
`CGPathMoveToPoint(path, NULL, $1, $2);`

![Convert to move](https://f.cloud.github.com/assets/1228143/2117060/1eaae7b8-90b2-11e3-8dc6-c5db33d429ec.png)

`L(-?\d+\.\d*),(-?\d+\.\d*)\s`
into
`CGPathAddLineToPoint(path, NULL, $1, $2);`
(there were no lines in this example but I still have the regex for other paths)

![Converting to lines](https://f.cloud.github.com/assets/1228143/2117061/32537438-90b2-11e3-9512-415a2451bc9b.png)

`C(-?\d+\.\d*),(-?\d+\.\d*)\s(-?\d+\.\d*),(-?\d+\.\d*)\s(-?\d+\.\d*),(-?\d+\.\d*)\s`
into
`CGPathAddCurveToPoint(path, NULL, $1, $2, $3, $4, $5, $6);`

![Converting to curves](https://f.cloud.github.com/assets/1228143/2117058/c2ee4e4c-90b1-11e3-97fe-1d9666ff37ca.png)

I did this separately for the "Load" part but I took both the "ing" and the dot over the "i" and made those into one shape instead of two.

When I tried the path in the app I felt that it was a bit to big so I scaled it down (in code) using:

```
CGAffineTransform t = CGAffineTransformMakeScale(0.7, 0.7); // It was slighly to big and I didn't feel like redoing it :D
```

You can see by the comment that there was a bit of manual work that I didn't feel was worth doing all over just to scale the paths down.
